#!\bin\bash
# i3 panel config. Powerline style.

panel_fifo="/tmp/i3_lemonbar_${USER}"
geometry="x30"
font="DejaVu Sans Mono for Powerline-10"
iconfont="FontAwesome-9"
res_w=$(xrandr | grep "current" | awk '{print $8a}')
snd_cha=$(amixer get Master | grep "Playback channels:" | awk '{if ($4 == "") {printf "%s: Playback", $3} else {printf "%s %s: Playback", $3, $4}}')

# Alarm settings
cpu_alert=75                        # % cpu use
net_alert=5                         # K net use

# update setting, in seconds (conky update in i3_lemonbar_conky
upd_vol=1                           # Volume update
upd_sid=5                           # WiFi update
upd_bat=1                           # Batery update

# color definitions 
color_back="#FF1D1F21"              # Default background
color_fore="#FFC5C8C6"              # Default foreground
color_head="#FFB5BD68"              # Background for first element
color_sec_b1="#FF282A2E"            # Background for section 1
color_sec_b2="#FF454A4F"            # Background for section 2
color_sec_b3="#FF60676E"            # Background for section 3
color_icon="#FF979997"              # For icons
color_mail="#FFCE935F"              # Background color for mail alert
color_chat="#FFCC6666"              # Background color for chat alert
color_cpu="#FF5F819D"               # Background color for cpu alert
color_net="#FF5E8D87"               # Background color for net alert
color_disable="#FF1D1F21"           # Foreground for disable elements
color_wsp="#FF8C9440"               # Background for selected workspace
color_error="#55550000"
color_success="#55005500"

#default space between sections
if [ ${res_w} -gt 1024 ]; then
  stab='  '
else
  stab=' '
fi

# Char glyps for powerline fonts
sep_left=""                        # Powerline separator left
sep_right=""                       # Powerline separator right
sep_l_left=""                      # Powerline light separator left
sep_l_right=""                     # Powerline light sepatator right

# Ionicon glyphs
icon_battery="    "
icon_clock=""                        # Clock icon
icon_calendar=""
icon_cpu=""                          # CPU icon
#icon_globe=""                        # Globe icon
icon_home=""                         # Home icon (also linux)
#icon_laptop=""                       # Laptop icon
icon_linux=""                        # Linux (Tux) icon
icon_mail=""                         # Email icon
icon_mem=""                          # Memory icon
icon_music=""                        # Music icon
icon_paw=""                          # Paw icon
icon_prog=""                         # Window icon
icon_shell=""                        # Shell icon
icon_vol=""                          # Volume icon
icon_mute=""
#icon_wsp=""                          # Workspace icon (paw duplicate for now)
icon_charging=""
icon_dl=""
icon_ul=""
icon_ssid=""
